# Generated by Django 5.2.8 on 2025-11-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pages',
            new_name='paginas',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publicacao',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='summary',
            new_name='sumario',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titulo',
        ),
    ]
