# Generated by Django 5.2.8 on 2025-11-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_author_nome_rename_author_book_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bio',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sumario',
            new_name='resumo',
        ),
    ]
